blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/Kenzo-Wada/boundary.nvim#readme
    about: Review the README for setup, configuration, and troubleshooting guidance.
