name: Format

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Stylua
        env:
          STYLUA_VERSION: "0.20.2"
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -L "https://github.com/JohnnyMorganz/StyLua/releases/download/v${STYLUA_VERSION}/stylua-linux-x86_64.zip" -o stylua.zip
          unzip stylua.zip -d stylua-bin
          sudo install stylua-bin/stylua /usr/local/bin/stylua

      - name: Run formatter
        run: make fmt

      - name: Ensure no diff
        run: git diff --exit-code
